#!/bin/bash
# This file is automatically generated for Replit deployment
# DO NOT EDIT THIS FILE MANUALLY

export NODE_ENV=production
echo "Starting BeAware.fyi in production mode..."
exec tsx server/index.ts
